name: Website

on:
  push:
    branches: [main]
    paths:
      - 'docs/web/**'
      - '.github/workflows/deploy-docs.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    uses: smnandre/.github/.github/workflows/Pages.yml@dde72e3a0d3ba29999360eab39e78a111d572b47
    with:
      path: docs/web
